services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - petsitter-app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - mongo
      - mysql
    networks:
      - petsitter-app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - petsitter-app
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PetSitter
      MYSQL_USER: evilla
      MYSQL_PASSWORD: 12345
    networks:
      - petsitter-app

networks:
  petsitter-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  mysql-data:
    driver: local
